---
title: Publications
---

layout: page
title: "Publications"
permalink: /Publications/

# Peer reviewed journal publications

Van Lankveld, Wim; Pat-El, Ron Jonathan; van Melick, Nicky; van Cingel, Robert; Staal, J Bart (2020). Is Fear of Harm (FoH) in Sports-Related Activities a Latent Trait? The Item Response Model Applied to the Photographic Series of Sports Activities for Anterior Cruciate Ligament Rupture (PHOSA-ACLR). Int. J. Environ. Res. Public Health, NA(NA), 13. DOI: 10.3390/ijerph17186764
Van den Bosch, Roxette M.; Espin, Christine A.; Pat-El, Ron Jonathan; Saab, Nadira (2019). Improving Teachers’ Comprehension of Curriculum-Based Measurement Progress-Monitoring Graphs. Journal of Learning Disabilities, 52(5), 413-427. DOI: 10.1177/0022219419856013
Mouw, J M; Saab, N; Pat-El, Ron Jonathan; Broek, P Van Den (2019). Student- and Task-Related Predictors of Primary-School Students ’ Perceptions of Cooperative Learning Activities. Pedagogische Studien, 96(NA), 98-122. DOI:
Nijsten, Johanna M. H.; Leontjevas, Ruslan; Pat-El, Ron Jonathan; Smalbrugge, Martin; Koopmans, Raymond T. C. M.; Gerritsen, Debby L. (2017). Apathy: Risk Factor for Mortality in Nursing Home Patients. Journal of the American Geriatrics Society, 65(10), 2182-2189. DOI: 10.1111/jgs.15007
de Vos, Jan Alexander; Brouwers, André; Schoot, Tineke; Pat-El, Ron; Verboon, Peter; Näring, Gérard (2016). Early career burnout among Dutch nurses: A process captured in a Rasch model. Burnout Research, 3(3), 55–62. DOI: 10.1016/j.burn.2016.06.001
Pat-El, Ron Jonathan; Tillema, Harm; Segers, Mien; Vedder, Paul (2014). Multilevel predictors of differing perceptions of Assessment for Learning practices between teachers and students. Assessment in Education: Principles, Policy & Practice, 22(2), 282-298. DOI: 10.1080/0969594X.2014.975675
Pat-El, Ron Jonathan; Tillema, Harm; Segers, Mien; Vedder, Paul (2013). Validation of Assessment for Learning Questionnaires for teachers and students.. The British journal of educational psychology, 83(NA), 98-113. DOI: 10.1111/j.2044-8279.2011.02057.x
Rizou, I; Nikaina, I; Pat-El, Ron Jonathan; Bazigou, H.; Kotsalis, C.; Paraskevoulakos, E; Papavasiliou, A (2010). Somatic complaints in patients with idiopathic with idiopathic epilepsies of childhood onset. Epilepsia, 51(NA), 157-157. DOI:
